export default function Head() {
    return (
        <>
            <title>MindWords - A place Where i can express myself</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>

            {/*Og*/}
            <meta property="og:url"
                  content="https://mindwords.info"/>
            <meta property="og:type" content="article"/>
            <meta property="og:title" content="MindWords - A place Where i can express myself"/>
            <meta property="og:description" content="How much does culture influence creative thinking?"/>
            <meta property="og:image"
                  content="/baseOg.png"/>
            <meta property="og:site_name" content="MindWords" />

            {/*twitter*/}
            <meta name="twitter:card" content="summary_large_image"/>
            <meta name="twitter:title" content="Title Of Your Content Here"/>
            <meta name="twitter:description" content="Description of your content here"/>
            <meta name="twitter:site" content="https://mindwords.info"/>
            <meta name="twitter:image" content="/baseOg.png"/>
        </>
    )
}
