import {getPost} from "@/service/post";

export default async function Head({params}:{params:{id:any}}) {
    const post = await getPost({postUrl:(params.id).trim()})
  return (
    <>
      <title>{post.data.title}</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
